name: Build dev container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/itavero/devcontainer-cpp
          cacheFrom: ghcr.io/itavero/devcontainer-cpp
          push: always
